@echo off
echo Iniciando el proyecto GEM...

echo Activando entorno virtual...
call .\env\Scripts\activate

echo Limpiando la base de datos...
call python manage.py flush --noinput

echo Realizando migraciones...
call python manage.py makemigrations
call python manage.py migrate

echo Poblando la base de datos...

echo 1. Creando administrador...
call python Poblar_database\administrador_bd.py

echo 2. Creando asignaturas base...
call python Poblar_database\asignaturas_bd.py

echo 3. Creando cursos...
call python Poblar_database\cursos_bd.py

echo 4. Creando docentes...
call python Poblar_database\docente_bd.py

echo 5. Creando horarios base...
call python Poblar_database\horario_bd.py

echo 6. Asignando asignaturas con horario completo (todos los cursos)...
call python Poblar_database\asignacion_horarios_completa.py

REM echo 7. Resolviendo conflictos de horarios...
REM call python Poblar_database\solucionador_conflictos.py

echo 7. Creando alumnos...
call python Poblar_database\alumnos_bd.py

call python Poblar_database\asignaturas_inscritas.py

echo Base de datos poblada exitosamente!

echo Iniciando servidor...
call python manage.py runserver 