# Generated by Django 5.0.2 on 2025-05-30 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesorjefe',
            name='clase',
        ),
        migrations.AddField(
            model_name='profesorjefe',
            name='curso',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jefatura_actual', to='Core.curso'),
        ),
        migrations.CreateModel(
            name='CursoProfesorJefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.OneToOneField(db_column='curso_id', on_delete=django.db.models.deletion.CASCADE, related_name='jefatura_historial', to='Core.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_jefe', to='Core.docente')),
            ],
        ),
    ]
