# Generated by Django 5.0.2 on 2025-05-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_usuario_password_alter_usuario_activador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='activador',
            field=models.BooleanField(default=True),
        ),
    ]
