# Generated by Django 5.2.1 on 2025-05-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_docente_id_remove_estudiante_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='nivel',
            field=models.PositiveSmallIntegerField(choices=[(1, '1°'), (2, '2°'), (3, '3°'), (4, '4°')], default=1),
            preserve_default=False,
        ),
    ]
