# Generated by Django 5.2.1 on 2025-06-23 12:22

import Core.models.comunicaciones
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_colegio_configuracioncolegio_anotacioncurso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('destinatarios_cursos', models.ManyToManyField(blank=True, related_name='comunicaciones', to='Core.curso')),
                ('destinatarios_usuarios', models.ManyToManyField(blank=True, related_name='comunicaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('leido_por', models.ManyToManyField(blank=True, help_text='Usuarios que han leído la comunicación', related_name='comunicaciones_leidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicación',
                'verbose_name_plural': 'Comunicaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoComunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=Core.models.comunicaciones.ruta_adjunto_comunicacion)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('comunicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='Core.comunicacion')),
            ],
            options={
                'verbose_name': 'Adjunto de Comunicación',
                'verbose_name_plural': 'Adjuntos de Comunicaciones',
            },
        ),
    ]
