# Generated by Django 5.0.6 on 2025-05-16 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.especialidad'),
        ),
    ]
