# Generated by Django 5.0.6 on 2025-05-28 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_usuario_activador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InscripcionElectivo',
        ),
    ]
