# Generated by Django 5.2.1 on 2025-06-25 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_comunicacion_adjuntocomunicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseCancelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cancelacion', models.DateField()),
                ('hora_cancelacion', models.TimeField()),
                ('motivo', models.CharField(choices=[('ENFERMEDAD', 'Enfermedad del docente'), ('PERSONAL', 'Motivos personales'), ('CAPACITACION', 'Capacitación o perfeccionamiento'), ('REUNION', 'Reunión institucional'), ('ACTIVIDAD_COLEGIO', 'Actividad del colegio'), ('EMERGENCIA', 'Emergencia'), ('OTRO', 'Otro motivo')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notificado_estudiantes', models.BooleanField(default=False)),
                ('clase_recuperada', models.BooleanField(default=False)),
                ('fecha_recuperacion', models.DateField(blank=True, null=True)),
                ('asignatura_impartida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.asignaturaimpartida')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.docente')),
            ],
            options={
                'verbose_name': 'Clase Cancelada',
                'verbose_name_plural': 'Clases Canceladas',
                'unique_together': {('asignatura_impartida', 'fecha_cancelacion', 'hora_cancelacion')},
            },
        ),
    ]
