# Generated by Django 5.2.1 on 2025-05-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_asignatura_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
