# Generated by Django 5.0.6 on 2025-05-16 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_docente_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clase',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='titulo',
        ),
        migrations.CreateModel(
            name='CursoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('sala', models.CharField(blank=True, max_length=50, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.docente')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='Core.cursoasignado'),
        ),
        migrations.CreateModel(
            name='EstudianteAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cursoasignado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'curso_asignado')},
            },
        ),
    ]
