# Generated by Django 5.0.2 on 2025-06-27 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0004_clasecancelada"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mensajechat",
            options={"ordering": ["-fecha_creacion"]},
        ),
        migrations.RemoveField(
            model_name="mensajechat",
            name="fecha_envio",
        ),
        migrations.AddField(
            model_name="mensajechat",
            name="es_publico",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mensajechat",
            name="fecha_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="mensajechat",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mensajes_chat",
                to="Core.usuario",
            ),
        ),
        migrations.CreateModel(
            name="ForoAsignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("contenido", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "es_anuncio",
                    models.BooleanField(
                        default=False, help_text="Si es un anuncio del profesor"
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foros",
                        to="Core.asignaturaimpartida",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Core.usuario"
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="MensajeForoAsignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Core.usuario"
                    ),
                ),
                (
                    "foro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="Core.foroasignatura",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha"],
            },
        ),
    ]
