# Generated by Django 5.0.2 on 2025-06-27 12:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0004_clasecancelada"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mensajechat",
            options={"ordering": ["-fecha_creacion"]},
        ),
        migrations.RemoveField(
            model_name="mensajechat",
            name="fecha_envio",
        ),
        migrations.AddField(
            model_name="mensajechat",
            name="es_publico",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mensajechat",
            name="fecha_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="mensajechat",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mensajes_chat",
                to="Core.usuario",
            ),
        ),
        migrations.DeleteModel(
            name="RecursoAsignatura",
        ),
    ]
