# Generated by Django 5.2.1 on 2025-05-30 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_profesorjefe_clase_profesorjefe_curso_and_more'),
        ('Core', '0004_alter_asignatura_nombre'),
    ]

    operations = [
    ]
