# Generated by Django 5.0.2 on 2025-06-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0005_alter_mensajechat_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foroasignatura",
            name="es_anuncio",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mensajechat",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
