# Generated by Django 5.0.6 on 2025-05-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_asignatura_remove_clase_docente_remove_clase_titulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=3, unique=True)),
            ],
        ),
    ]
