# Generated by Django 5.2.1 on 2025-06-04 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_merge_20250530_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(choices=[('Clase', 'Clase'), ('Recreo', 'Recreo'), ('Almuerzo', 'Almuerzo')], max_length=10)),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('asignatura_impartida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.asignaturaimpartida')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='Core.curso')),
            ],
            options={
                'unique_together': {('curso', 'dia', 'hora_inicio')},
            },
        ),
    ]
