# Generated by Django 5.0.2 on 2025-06-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0006_alter_foroasignatura_es_anuncio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='ForoAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('es_anuncio', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.usuario')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foros', to='Core.asignaturaimpartida')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MensajeForoAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.usuario')),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='Core.foroasignatura')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
